#!/usr/bin/env bash
# ============================================================================
# fix_critical_skills_v2.sh — combined extraction + injection (idempotent)
#
# Fixes two bugs from v1:
#   1. The `awk -v dir="$directive"` call failed on multi-line strings.
#      Replaced with head/tail file slicing.
#   2. `set -e` would terminate after the first awk failure, leaving
#      sources 2–N unprocessed. v2 reaches every source even if one fails.
#
# Per source it:
#   - Backs up SKILL.md → SKILL_pre_repair.md (only if no backup exists)
#   - Generates VERBATIM_REFERENCE.md from source files preserved on disk
#   - Injects the trust directive into SKILL.md (idempotent via marker check)
# ============================================================================

set -u  # no -e — we want to continue past per-source failures

SKILLS_DIR="${1:-./skills}"

CRITICAL=(
    "discovery-and-indexing|explorer.oobeprotocol.ai_docs_core_discovery|web"
    "x402-client|AceDataCloud_X402Client|repo"
    "explorer.oobeprotocol.ai_docs_sdk_escrow-api|explorer.oobeprotocol.ai_docs_sdk_escrow-api|web"
    "x402-payments|explorer.oobeprotocol.ai_docs_core_payments|web"
    "acedatacloud-mcps|AceDataCloud_MCPs|repo"
)

G=$'\e[32m'; Y=$'\e[33m'; R=$'\e[31m'; B=$'\e[34m'; N=$'\e[0m'

log()  { echo "${B}[$(date +%H:%M:%S)]${N} $*"; }
ok()   { echo "  ${G}✓${N} $*"; }
warn() { echo "  ${Y}⚠${N} $*"; }
err()  { echo "  ${R}✗${N} $*" >&2; }

[[ -d "$SKILLS_DIR" ]] || { err "Skills dir not found: $SKILLS_DIR"; exit 1; }

# Write the trust directive to a temp file once — referenced via cat into place
DIR_FILE=$(mktemp)
trap "rm -f $DIR_FILE" EXIT
cat > "$DIR_FILE" <<'DIRECTIVE'

<!-- VERBATIM-DIRECTIVE-V1 -->
> **⚠ TRUSTED API REFERENCE — read this before generating any code**
>
> This skill's narrative sections were generated by an LLM and may contain
> **paraphrased** API references. For ANY code generation involving:
>
> - method names / function names
> - parameter names or parameter order
> - parameter types or return types
> - constants, enum values, struct/interface fields
> - configuration keys or environment variable names
> - file paths inside the source repository
>
> You **MUST** consult the companion file `VERBATIM_REFERENCE.md` in this
> same directory. It contains literal, character-for-character extraction
> from the actual source code with no LLM interpretation.
>
> **Rule:** if a method signature appears in `VERBATIM_REFERENCE.md`, use
> it exactly as written. If it appears only in `SKILL.md` and NOT in the
> verbatim file, treat it as unverified — ask the user before writing
> code that depends on it.

DIRECTIVE

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Critical skill repair v2 (extraction + injection)"
echo "═══════════════════════════════════════════════════════════"
echo "  Skills directory: $SKILLS_DIR"
echo ""

# ─────────────────────────────────────────────────────────
# extract_repo_api — full content of common entry points + per-language
# signatures + manifests. Output to stdout.
# ─────────────────────────────────────────────────────────
extract_repo_api() {
    local src_root="$1/files"
    [[ -d "$src_root" ]] || { warn "no files/ at $src_root"; return; }

    # Common entry-point dumps (full content, capped at 50KB)
    echo ""
    echo "## Entry points (verbatim)"
    echo ""
    local entries=("src/index.ts" "src/index.js" "src/main.ts" "src/main.py"
                   "src/lib.rs" "src/main.rs" "index.ts" "index.js" "main.py"
                   "__init__.py" "lib/index.ts" "lib/index.js")
    for cand in "${entries[@]}"; do
        local f="$src_root/$cand"
        if [[ -f "$f" ]]; then
            local size; size=$(wc -c < "$f")
            if (( size < 50000 )); then
                local ext="${cand##*.}"
                echo "### \`$cand\`"
                echo ""
                echo "\`\`\`$ext"
                cat "$f"
                echo "\`\`\`"
                echo ""
            fi
        fi
    done

    # TypeScript / JavaScript exports
    echo ""
    echo "## TypeScript / JavaScript exports (verbatim)"
    echo ""
    find "$src_root" -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.mts" -o -name "*.cts" \) 2>/dev/null \
        | grep -vE "node_modules|\.test\.|\.spec\.|__tests__|\.d\.ts$" \
        | sort | while IFS= read -r f; do
            local relpath="${f#$src_root/}"
            if grep -qE "^(export|declare) " "$f" 2>/dev/null; then
                echo "### \`$relpath\`"
                echo ""
                echo '```typescript'
                { awk '
                    /^(export|declare) / { capturing=1; depth=0 }
                    capturing {
                        print
                        n_open = gsub(/\{/, "{")
                        n_close = gsub(/\}/, "}")
                        depth += n_open - n_close
                        if (depth == 0 && /[;}]$/) { capturing=0; print "" }
                    }
                ' "$f" 2>/dev/null | head -120 2>/dev/null; } || true
                echo '```'
                echo ""
            fi
        done

    # Python defs/classes
    echo ""
    echo "## Python definitions (verbatim)"
    echo ""
    find "$src_root" -type f -name "*.py" 2>/dev/null \
        | grep -vE "__pycache__|test_|_test\.py|tests/" \
        | sort | while IFS= read -r f; do
            local relpath="${f#$src_root/}"
            if grep -qE "^(async def|def|class) " "$f" 2>/dev/null; then
                echo "### \`$relpath\`"
                echo ""
                echo '```python'
                { grep -nE "^(async def|def|class|@[A-Za-z])" "$f" 2>/dev/null \
                    | head -80 2>/dev/null \
                    | sed 's/^[0-9]*://' 2>/dev/null; } || true
                echo '```'
                echo ""
            fi
        done

    # Rust / Go signatures
    echo ""
    echo "## Rust / Go signatures (verbatim)"
    echo ""
    find "$src_root" -type f \( -name "*.rs" -o -name "*.go" \) 2>/dev/null \
        | grep -vE "_test\.go|tests/" | sort | while IFS= read -r f; do
            local relpath="${f#$src_root/}"
            if grep -qE "^(pub fn|pub struct|pub enum|pub trait|func |type )" "$f" 2>/dev/null; then
                echo "### \`$relpath\`"
                echo ""
                local ext="${f##*.}"
                echo "\`\`\`$ext"
                { grep -E "^(pub fn|pub struct|pub enum|pub trait|func |type )" "$f" 2>/dev/null | head -50 2>/dev/null; } || true
                echo '```'
                echo ""
            fi
        done

    # Manifest files
    echo ""
    echo "## Package manifests & config (verbatim)"
    echo ""
    for m in "package.json" "pyproject.toml" "Cargo.toml" "go.mod" "tsconfig.json"; do
        local f="$src_root/$m"
        if [[ -f "$f" ]]; then
            echo "### \`$m\`"
            echo ""
            local ext="${m##*.}"
            echo "\`\`\`$ext"
            { head -100 "$f" 2>/dev/null; } || true
            echo '```'
            echo ""
        fi
    done
}

# ─────────────────────────────────────────────────────────
# extract_doc_code — fenced code blocks + inline identifiers from docs
# ─────────────────────────────────────────────────────────
extract_doc_code() {
    local src_root="$1/files"
    [[ -d "$src_root" ]] || { warn "no files/ at $src_root"; return; }

    echo ""
    echo "## All code blocks from documentation (verbatim)"
    echo ""
    find "$src_root" -type f -name "*.md" 2>/dev/null | sort | while IFS= read -r f; do
        local relpath="${f#$src_root/}"
        if grep -q '^```' "$f" 2>/dev/null; then
            local block_count
            block_count=$(grep -c '^```' "$f" 2>/dev/null || echo 0)
            block_count=$((block_count / 2))
            echo "### From \`$relpath\` ($block_count code blocks)"
            echo ""
            awk '
                /^#{1,6} / { current_header = $0 }
                /^```/ && !in_block {
                    in_block = 1
                    if (current_header != "" && current_header != last_emitted_header) {
                        print "**" current_header "**"
                        print ""
                        last_emitted_header = current_header
                    }
                    print
                    next
                }
                in_block && /^```/ {
                    in_block = 0
                    print
                    print ""
                    next
                }
                in_block { print }
            ' "$f" 2>/dev/null
        fi
    done

    echo ""
    echo "## Inline code identifiers (verbatim)"
    echo ""
    echo '```'
    {
        find "$src_root" -type f -name "*.md" 2>/dev/null -exec cat {} \; 2>/dev/null \
            | grep -oE '`[A-Za-z_][A-Za-z0-9_.()/-]{3,80}`' 2>/dev/null \
            | sort -u 2>/dev/null \
            | head -200 2>/dev/null
    } || true
    echo '```'
}

# ─────────────────────────────────────────────────────────
# inject_directive — head/tail approach (no awk -v bug)
# ─────────────────────────────────────────────────────────
inject_directive() {
    local skill_md="$1"
    if [[ ! -f "$skill_md" ]]; then
        err "missing: $skill_md"
        return 1
    fi
    if [[ ! -s "$skill_md" ]]; then
        err "SKILL.md is empty"
        return 1
    fi
    if grep -qF "VERBATIM-DIRECTIVE-V1" "$skill_md" 2>/dev/null; then
        warn "directive already present, skipping"
        return 0
    fi

    # Try to find closing --- of YAML frontmatter
    local end_line=""
    if head -1 "$skill_md" | grep -q '^---'; then
        end_line=$(head -50 "$skill_md" | awk 'NR>1 && /^---[[:space:]]*$/ {print NR; exit}')
    fi

    if [[ -n "$end_line" ]]; then
        {
            head -n "$end_line" "$skill_md"
            cat "$DIR_FILE"
            tail -n +"$((end_line + 1))" "$skill_md"
        } > "$skill_md.tmp"
        mv "$skill_md.tmp" "$skill_md"
        ok "directive injected after frontmatter (line $end_line)"
    else
        # No frontmatter — prepend at very top
        {
            cat "$DIR_FILE"
            cat "$skill_md"
        } > "$skill_md.tmp"
        mv "$skill_md.tmp" "$skill_md"
        ok "directive prepended (no YAML frontmatter detected)"
    fi
    return 0
}

# ─────────────────────────────────────────────────────────
# Main loop — process each source independently, no early exit
# ─────────────────────────────────────────────────────────
TOTAL=${#CRITICAL[@]}
COMPLETE=0
PARTIAL=0
FAILED=0

for entry in "${CRITICAL[@]}"; do
    IFS='|' read -r skill_subdir source_subdir kind <<< "$entry"

    skill_dir="$SKILLS_DIR/$skill_subdir"
    source_dir="$SKILLS_DIR/.sources/$source_subdir"
    skill_md="$skill_dir/SKILL.md"
    verbatim_md="$skill_dir/VERBATIM_REFERENCE.md"
    backup_md="$skill_dir/SKILL_pre_repair.md"

    echo ""
    echo "──────────────────────────────────────────────────────────"
    echo "  $skill_subdir ($kind)"
    echo "──────────────────────────────────────────────────────────"

    if [[ ! -f "$skill_md" ]]; then
        err "missing SKILL.md: $skill_md"
        FAILED=$((FAILED + 1))
        continue
    fi
    if [[ ! -d "$source_dir" ]]; then
        err "missing source bundle: $source_dir"
        FAILED=$((FAILED + 1))
        continue
    fi

    step_ok=0

    # Step 1: Backup
    if [[ -f "$backup_md" ]]; then
        warn "backup already exists at SKILL_pre_repair.md"
    else
        cp "$skill_md" "$backup_md" && {
            ok "backed up SKILL.md → SKILL_pre_repair.md"
            step_ok=$((step_ok + 1))
        }
    fi

    # Step 2: Verbatim extraction (re-extract even if exists — cheap)
    log "extracting verbatim source content..."
    {
        echo "# Verbatim source reference for $skill_subdir"
        echo ""
        echo "**Skill**: \`$skill_md\`"
        echo "**Source bundle**: \`$source_dir\`"
        echo "**Generated**: $(date -Iseconds 2>/dev/null || date)"
        echo ""
        echo "> ⚠ Content below was extracted DIRECTLY from source files."
        echo "> No LLM in the loop. Use as source of truth for code generation."
        echo ""
        echo "---"
        if [[ "$kind" == "repo" ]]; then
            extract_repo_api "$source_dir"
        else
            extract_doc_code "$source_dir"
        fi
    } > "$verbatim_md"
    if [[ -s "$verbatim_md" ]]; then
        local_lines=$(wc -l < "$verbatim_md")
        local_bytes=$(wc -c < "$verbatim_md")
        ok "VERBATIM_REFERENCE.md: $local_lines lines, $local_bytes bytes"
        step_ok=$((step_ok + 1))
    else
        err "verbatim extraction produced empty output"
    fi

    # Step 3: Directive injection (uses head/tail, no awk -v bug)
    if inject_directive "$skill_md"; then
        step_ok=$((step_ok + 1))
    fi

    if (( step_ok >= 2 )); then
        COMPLETE=$((COMPLETE + 1))
    else
        PARTIAL=$((PARTIAL + 1))
    fi
done

# ─────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Repair summary"
echo "═══════════════════════════════════════════════════════════"
echo "  ${G}Complete: $COMPLETE${N}    Partial: $PARTIAL    Failed: $FAILED    of $TOTAL"
echo ""
echo "  Per-skill final status:"
echo ""
printf "    %-50s %12s %10s\n" "skill" "verbatim" "directive"
printf "    %-50s %12s %10s\n" "─────────────────────────────────────────────" "────────────" "──────────"
for entry in "${CRITICAL[@]}"; do
    IFS='|' read -r skill_subdir _ _ <<< "$entry"
    v_size="—"; v_dir="—"
    if [[ -f "$SKILLS_DIR/$skill_subdir/VERBATIM_REFERENCE.md" ]]; then
        v_size=$(wc -c < "$SKILLS_DIR/$skill_subdir/VERBATIM_REFERENCE.md")
        v_size="${v_size}B"
    fi
    if grep -qF "VERBATIM-DIRECTIVE-V1" "$SKILLS_DIR/$skill_subdir/SKILL.md" 2>/dev/null; then
        v_dir="${G}✓${N}"
    else
        v_dir="${R}✗${N}"
    fi
    printf "    %-50s %12s %10b\n" "$skill_subdir" "$v_size" "$v_dir"
done

echo ""
echo "  ${G}Next:${N} attach BOTH SKILL.md and VERBATIM_REFERENCE.md from each"
echo "  directory when loading skills into Claude/Cursor. The trust directive"
echo "  at the top of SKILL.md will tell the AI to prefer the verbatim file"
echo "  for any code generation involving exact identifiers."
echo ""
